#!/bin/bash

TMP_DIR="/tmp"
PREVIOUS_VALUE_FILE="$TMP_DIR/previous_value.txt"

# Function to get the previous value from a file
get_previous_value() {
  if [ -e "$PREVIOUS_VALUE_FILE" ]; then
    cat "$PREVIOUS_VALUE_FILE"
  else
    echo ""
  fi
}

# Function to save the current value to a file
save_current_value() {
  echo "$1" > "$PREVIOUS_VALUE_FILE"
}

# Get the current and previous values
current_value=$(brillo | awk '{gsub(".00", ""); print $1}')
previous_value=$(get_previous_value)

# Print the current value to the console
echo "$current_value%"

# Compare values and send notification if they are different
if [ "$current_value" != "$previous_value" ]; then
  # Send notification
  # notify-send "Brillo Result" "$current_value"
  
  # Save the current value
  save_current_value "$current_value"
fi

