#!/bin/bash

# Terminate already running bar instances
# killall -q polybar

# wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# launch polybar
polybar main &
#sleep 1
#polybar top_right &

if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then
	polybar top_external &
fi
