#! /bin/sh

# Default 1 monitor with 6 workspaces
#	for monitor in "$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"; do
#		bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
#	done

if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then 
	xrandr --output DP-2 --primary --mode 2560x1600 --rate 165 --rotate normal --output HDMI-1-0 --mode 2560x1440 --rate 100 --rotate normal --right-of DP-2
fi

bspc monitor DP-2 -d 1 2 3 4 5 6
bspc monitor HDMI-1-0 -d 7 8 9 0

## bspwm config ##

## external rules
bspc config external_rules_command "$HOME"/.config/bspwm/scripts/ExternalRules

bspc config window_gap			6
bspc config split_ratio			0.51
bspc config single_monocle		true
bspc config borderless_monocle		false
bspc config gapless_monocle		false

bspc config focus_follows_pointer	true
bspc config pointer_follows_focus	false
bspc config pointer_motion_interval	5
bspc config pointer_modifier		mod4
bspc config pointer_action1		move
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner

bspc config focused_border_color   "#DB93F9"
bspc config normal_border_color	   "#282A36"
bspc config active_border_color	   "#8BE9FD"
bspc config presel_feedback_color  "#50FA7B"

bspc rule -a scratch sticky=on state=floating focus=on

## autostart ##

# Terminate already running polybar, sxhkd and dunst instances
processes=("polybar" "sxhkd" "dunst")

	for process in "${processes[@]}"; do
		if pgrep -f "$process"; then
			pkill -9 -f "$process" > /dev/null; sleep 0.1
		fi
	done


## hotkey daemon
sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &
## notificationn daemon
dunst -config "$HOME"/.config/dunst/dunstrc &
## network manager applet
nm-applet &
## polybar launcher
polylaunch &
# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }
## fix cursor
xsetroot -cursor_name left_ptr
xset r rate 200 50
