#!/usr/bin/env bash

case "$1" in

	--terminal)
		kitty
		;;
	--floating)
		alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=90
    ;;
  --soundcontrol)
		pavucontrol
esac
